server:
  port: 8003
  servlet:
    context-path: /producer

spring:
  application:
    name: hanyi-producer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        metadata:
          service.type: gray

